### ISSUE TITLE
Inconsistency between `valid_upc_e?` and `from_upc_e`

### ISSUE THREAD

**Issue by yosi-dediashvili** [jreut/gtin#1]
When you call `Gtin.valid_upc_e?("2012345")`, you'd expect the corresponding `Gtin.from_upc_e("2012345")` call to return a GTIN. 

The issue is that this is not a valid UPC-E  - the check digit should be 2, not 5. Therefor, calling `from_upc_e` is throwing `invalid UPC-E` error.

I'd suggest going on the safe side with this, and just make the checksum validation also part of the `valid_upc_e?` process, given that the structure of the input seems valid.

**Comment by yosi-dediashvili** [comment]
I might be able to contribute with a PR, but putting it here for now.

**Comment by jreut** [comment]
Hello, and thank you for submitting this issue here! I apologize, but I am no longer developing this project. I plan to delete this repository in one week. If you like, feel free to clone it and use it as permitted under this project's license. I appreciate your effort in submitting a pull request!

Cheers,
Jordan
